### ISSUE TITLE
Drop Python 2 Support

### ISSUE THREAD

**Issue by awdeorio** [awdeorio/mailmerge#129]
Python 2 is [deprecated as of 2020](https://www.python.org/downloads/release/python-2718/).  Dropping Python 2 support would simplify virtually every future change, since it invariably causes annoying and tricky-to-fix problems.  Just one example is in my work on #81.  Tests pass on Python 3 and fail on Python 2.

## Todo
- [x] Remove imports `future`, `backports`, `pathlib2`
- [x] Update CI config
- [x] Update dependencies in `setup.py`
- [x] Remove monkey patch `header_encode_patched` 
- [x] Replace `u""` with `""`
- [x] Remove `coding=utf-8` from all files
- [x] Remove code from tests that accounts for newline differences produced by the email library in Python 2 vs. 3
- [x] Recursively search for "python 2"
- [x] Recursively search for "utf.?8"
- [x] Remove "inherit from object" and update pylint directives
- [x] Update Contributing docs
- [ ] Bump major version before release

**Comment by awdeorio** [comment]
@seshrs Do you see any unintended consequences here?

**Comment by awdeorio** [comment]
Under way in `drop-python2-support`

**Comment by seshrs** [comment]
This is a great initiative! I think you’ve covered everything I would have thought of :)

**Comment by seshrs** [comment]
Edit: Maybe also update the README for users whose default Python path still points to Python 2? (Like users who set up on older versions of MacOS? I don’t actually know if it’s still bundled in newer versions.)

**Comment by awdeorio** [comment]
> Edit: Maybe also update the README for users whose default Python path still points to Python 2? (Like users who set up on older versions of MacOS? I don’t actually know if it’s still bundled in newer versions.)

Brainwave!  I think that adding this to the `setup.py` should do the trick:
```python
    python_requires='>=3.4',
```
